name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - uses: codecov/codecov-action@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        token: ${{ secrets.CODECOV_TOKEN }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run test:ci
